# Generated by Django 3.1.6 on 2023-03-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.JSONField(default=None, null=True)),
                ('username', models.CharField(default=None, max_length=140, null=True)),
                ('password', models.CharField(default=None, max_length=255, null=True)),
                ('firstname', models.CharField(default='Unknown', max_length=140, null=True)),
                ('lastname', models.CharField(default=None, max_length=140, null=True)),
                ('phonenumber', models.CharField(default=None, max_length=25, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
