# Generated by Django 3.1.6 on 2023-03-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default=None, max_length=140, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
