# Generated by Django 3.1.6 on 2023-03-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default=None, max_length=140, null=True, unique=True),
        ),
    ]
