version: '3.6'

services:
  testdb:
    container_name: testdb
    image: postgres:10.7
    environment:
      POSTGRES_PASSWORD: admin#afifa  # superuser password, username is postgres
      POSTGRES_DB: test_afifa  # default db created when image first started
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:6.0.1
    volumes:
      - ./data/redis:/data

  celery:
    container_name: celery
    image: test_afifa_mainapp:latest  # use web container image
    command: celery -A test_afifa worker -l info --uid=nobody --gid=nogroup
    volumes:
    - ./:/usr/src/app/
    depends_on:
      - testdb
      - redis
    restart: always
    env_file:
      - project_config.env

  mainapp:
    container_name: mainapp
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - testdb
      - redis
      - celery
    env_file:
      - project_config.env
    command: bash -c "python manage.py makemigrations
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
