version: '3.6'

services:
  db:
    container_name: db
    image: postgres:10.7
    environment:
      POSTGRES_USER: afifa
      POSTGRES_PASSWORD: admin@afifa  # superuser password, username is postgres
      POSTGRES_DB: test_afifa  # default db created when image first started
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:6.0.1
    volumes:
      - ./data/redis:/data

  celery:
    container_name: celery-app-tasks
    image: test_afifa_web:latest  # use web container image
    command: celery -A test_afifa worker -l info --uid=nobody --gid=nogroup
    volumes:
    - ./:/usr/src/app/
    depends_on:
      - db
      - redis
    restart: always
    env_file:
      - project_config.env

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
    env_file:
      - project_config.env
    command: ./manage.py runserver 0.0.0.0:8000
